### Create a USER 1
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Bob",
  "email" : "bob@email.com",
  "password": "bob"
}
### Create a USER 2
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Fred",
  "email" : "fred@email.com",
  "password": "fred"
}

###List USERS
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU5NmVjYTQtOTQ0NS00NmY3LWExNDYtMzg2M2Q1YmQ3YWU0IiwidXNlcl9uYW1lIjoiQm9iIiwidXNlcl9lbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE2MjAzMTAzODgsImV4cCI6MTYyMDMxMDQxOH0.ae6yETgMWgsVAwG3e1pssuHDUqjoc0ob2CUWLyKFsEw
###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"bob@email.com",
  "password":"bob"
}

###REFRESH TOKENS
GET http://localhost:5000/api/auth/refresh_token

###

DELETE http://localhost:5000/api/auth/refresh_token
###

DELETE http://localhost:5000/api/users
